# Generated by Django 5.0.5 on 2024-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True)),
                ('remainder', models.IntegerField(default=0)),
                ('characteristics', models.CharField(max_length=200)),
            ],
        ),
    ]
