# Generated by Django 5.0.5 on 2024-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='characteristics',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
